version: "3.0"

services:
  app:
    build: ./src/app
    environment:
      - LOG_LEVEL=${APP_LOG_LEVEL}
    volumes:
      - ./src/app:/app
      - ./logs/php:/var/log/php
      - ./logs/app:/log
    restart: always

  nginx:
    build: ./containers/nginx
    ports:
      - 80:80
    volumes:
      - ./logs/nginx/:/var/log/nginx
    command: nginx -g "daemon off;"
    restart: always
